import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, symlink, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { Readable } from 'node:stream';
import { createUserStore } from '../lib/users.js';
import { createUiStateStore } from '../lib/ui-state.js';
import { createApiRouter } from '../api/index.js';
import { createAuthService } from '../api/auth.js';
import { canAccessProject } from '../lib/project-access.js';

test('member project grants apply to lists, reads, mutations, files, and creation', async t => {
 const dir=await mkdtemp(path.join(tmpdir(),'office-project-access-'));
 const users=createUserStore(path.join(dir,'users.sqlite'));
 const state=createUiStateStore(path.join(dir,'state.sqlite'));
 t.after(async()=>{ users.close(); state.close(); await rm(dir,{recursive:true,force:true}); });
 const root=path.join(dir,'files'); await mkdir(root);
 const admin=await users.register({email:'admin@example.com',name:'Admin',password:'pass'});
 const person=await users.register({email:'member@example.com',name:'Member',password:'pass'});
 const allowed=state.createProject({name:'Allowed'}), denied=state.createProject({name:'Denied'});
 users.update(person.id,{role:'member',projectIds:[allowed.id]});
 const {token}=await users.login({email:person.email,password:'pass'});
 const adminSession=await users.login({email:admin.email,password:'pass'});
 const auth=createAuthService({userStore:users,getProjects:()=>state.getProjects()});
 const router=createApiRouter({uiStateStore:state,userStore:users,sharedWorkspaceRoot:root,subAgentManager:{listWorkers:()=>[],listTasks:()=>[]},officeChatService:{list:()=>({messages:[],members:[]})}});
 const request=async(url,{method='GET',body,asAdmin=false}={})=>{
  const req=Readable.from(body?[Buffer.from(JSON.stringify(body))]:[]);req.method=method;
  req.headers={cookie:`office_session=${asAdmin ? adminSession.token : token}`,'content-type':'application/json'};req.socket={remoteAddress:'test'};
  const result={};const res={setHeader(){},writeHead(status){result.status=status},end(value){result.body=value?JSON.parse(value):null}};
  const parsed=new URL(url,'http://office.test');
  if(await auth.handle(req,res,parsed))return result;
  await router(req,res,parsed);return result;
 };
 assert.deepEqual((await request('/api/projects')).body.projects.map(p=>p.id),[allowed.id]);
 for(const api of ['tasks','chat','memory','operations','shared-workspace']) {
  assert.equal((await request(`/api/${api}?projectId=${denied.id}`)).status,403,api);
 }
 assert.equal((await request('/api/tasks')).status,403);
 assert.equal((await request(`/api/tasks?projectId=${allowed.id}`)).status,200);
 const hidden=state.createOfficeTask({title:'Secret',projectId:denied.id});
 assert.equal((await request('/api/tasks',{method:'DELETE',body:{id:hidden.id,projectId:allowed.id,action:'delete'}})).status,403);
 assert.equal((await request('/api/tasks',{method:'POST',body:{title:'Bad dependency',projectId:allowed.id,dependsOn:[hidden.id]}})).status,403);
 assert.equal((await request('/api/tasks',{method:'POST',body:{title:'Allowed task',projectId:allowed.id}})).status,201);
 assert.equal((await request('/api/projects',{method:'PUT',body:{id:denied.id,name:'Attempt'}})).status,403);
 assert.equal((await request(`/files/${denied.id}/secret.txt`)).status,403);
 assert.equal((await request(`/downloads/tasks/${denied.id}/${hidden.id}.zip`)).status,403);
 await mkdir(path.join(root,allowed.id));await mkdir(path.join(root,denied.id));
 await writeFile(path.join(root,denied.id,'secret.txt'),'secret');
 await symlink(path.join(root,denied.id,'secret.txt'),path.join(root,allowed.id,'link.txt'));
 assert.equal((await request(`/api/shared-workspace-file?path=${allowed.id}/link.txt`)).status,403);
 assert.equal((await request('/api/workspace-tree')).status,403);
 assert.equal((await request('/api/users',{method:'PATCH',asAdmin:true,body:{id:person.id,projectIds:['missing']}})).status,400);
 assert.equal((await request('/api/users',{method:'PATCH',asAdmin:true,body:{id:person.id,projectIds:[]}})).status,200);
 assert.deepEqual((await request('/api/projects')).body.projects,[]);
 assert.equal((await request(`/api/tasks?projectId=${allowed.id}`)).status,403);
 const created=await request('/api/projects',{method:'POST',body:{name:'My new project'}});
 assert.equal(created.status,201);
 assert.deepEqual(users.session(token).projectIds,[created.body.project.id]);
 assert.equal((await request(`/api/tasks?projectId=${created.body.project.id}`)).status,200);
 assert.equal((await request('/api/projects',{asAdmin:true})).body.projects.length,4);
 assert.equal((await request('/api/users',{method:'PATCH',body:{id:person.id,projectIds:null}})).status,403);
 assert.equal(canAccessProject(users.session(token),denied.id),false);
 const reopened=createUserStore(path.join(dir,'users.sqlite'));
 assert.deepEqual(reopened.session(token).projectIds,[created.body.project.id]);
 reopened.close();
 users.update(person.id,{projectIds:null});
 assert.equal((await request('/api/projects')).body.projects.length,4);
});
