import fs from 'node:fs';
import assert from 'node:assert/strict';
const targets = await (await fetch('http://127.0.0.1:9344/json')).json();
const ws = new WebSocket(targets.find(t => t.type === 'page').webSocketDebuggerUrl);
await new Promise(r => ws.onopen = r);
let id=0; const pending=new Map();
ws.onmessage=e=>{ const m=JSON.parse(e.data); if(m.id){const p=pending.get(m.id); pending.delete(m.id); m.error?p.reject(m.error):p.resolve(m.result);} };
const send=(method,params={})=>new Promise((resolve,reject)=>{pending.set(++id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
const pause=()=>new Promise(r=>setTimeout(r,300));
await send('Page.enable');
await send('Page.addScriptToEvaluateOnNewDocument',{source:`window.testUser=null; window.testSetup=false; window.calls=[]; const realFetch=window.fetch.bind(window); window.fetch=async (url,opts)=>{if(!String(url).startsWith('/api/'))return realFetch(url,opts);window.calls.push(url); let data={}; if(url==='/api/auth/session')data={user:window.testUser,needsSetup:window.testSetup}; if(url==='/api/auth/login'){window.testUser={id:'test',name:'Test User',email:'test@example.com',role:'pending'};} if(url==='/api/users')data={users:[window.testUser]};return new Response(JSON.stringify(data),{status:200,headers:{'content-type':'application/json'}});};`});
await send('Emulation.setDeviceMetricsOverride',{width:1440,height:960,deviceScaleFactor:1,mobile:false});
await send('Page.navigate',{url:'http://127.0.0.1:8134/account'});await pause();
assert.equal(await evaluate(`document.querySelector('h1').textContent`),'Welcome back');
assert.deepEqual(await evaluate(`performance.getEntriesByType('resource').filter(x=>x.name.endsWith('.mjs')).map(x=>new URL(x.name).pathname).sort()`),['/account.mjs','/lib/user-avatars.mjs']);
assert.equal(await evaluate(`document.querySelector('.sidebar')`),null);
await evaluate(`document.querySelector('.password-field button').click()`);
assert.equal(await evaluate(`document.querySelector('[name=password]').type`),'text');
fs.writeFileSync('screenshots/account-login.png',Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
await evaluate(`document.querySelector('.account-actions button').click()`);
assert.equal(await evaluate(`document.querySelector('h1').textContent`),'Create your account');
await evaluate(`document.querySelector('[name=name]').value='Test User';document.querySelector('[name=email]').value='test@example.com';document.querySelector('[name=password]').value='password';document.querySelector('[name=confirmation]').value='mismatch';document.querySelector('form').requestSubmit()`);await pause();
assert.equal(await evaluate(`document.querySelector('#account-message').textContent`),'Passwords do not match.');
assert.equal(await evaluate(`calls.includes('/api/auth/register')`),false);
await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
assert.equal(await evaluate(`document.documentElement.scrollWidth<=innerWidth`),true);
await evaluate(`document.querySelector('[name=confirmation]').value='password';document.querySelector('#account-message').hidden=true`);
fs.writeFileSync('screenshots/account-register-mobile.png',Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
await evaluate(`document.querySelector('form').requestSubmit()`);await pause();
assert.equal(await evaluate(`document.querySelector('.account-notice h2').textContent`),'Awaiting approval');
assert.equal(await evaluate(`document.documentElement.scrollWidth<=innerWidth`),true);
await evaluate(`(async()=>{window.testUser.role='admin'; await import('/account.mjs').then(m=>m.renderAccount(document.querySelector('#account-view')))})()`);await pause();
assert.equal(await evaluate(`document.querySelectorAll('.user-card').length`),1);
assert.equal(await evaluate(`document.querySelector('.enter-office').getAttribute('href')`),'/');
assert.equal(await evaluate(`document.documentElement.scrollWidth<=innerWidth`),true);
await evaluate(`(async()=>{window.testUser=null;window.testSetup=true; await import('/account.mjs').then(m=>m.renderAccount(document.querySelector('#account-view')))})()`);
assert.equal(await evaluate(`document.querySelector('h1').textContent`),'Create administrator account');
console.log('PASS: isolated script loading, login/register, visibility toggle, confirmation validation, pending approval, admin controls, first-run setup, mobile overflow. Auth responses mocked; real API covered by users tests.');
await send('Browser.close'); ws.close();
