import fs from 'node:fs';
import assert from 'node:assert/strict';
const targets = await (await fetch('http://127.0.0.1:9337/json')).json();
const ws = new WebSocket(targets.find(t => t.type === 'page').webSocketDebuggerUrl);
await new Promise(r => ws.onopen = r);
let id = 0; const pending = new Map();
ws.onmessage = e => { const m = JSON.parse(e.data); if (m.id) { const p = pending.get(m.id); pending.delete(m.id); m.error ? p.reject(m.error) : p.resolve(m.result); } };
const send = (method, params={}) => new Promise((resolve,reject) => { pending.set(++id,{resolve,reject}); ws.send(JSON.stringify({id,method,params})); });
const evaluate = async expression => { const r = await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true}); if(r.exceptionDetails) throw Error(r.exceptionDetails.text); return r.result.value; };
const pause = () => new Promise(r => setTimeout(r,700));
await send('Page.enable');
await send('Page.addScriptToEvaluateOnNewDocument',{source:`history.replaceState(null,'','/settings'); const originalFetch = window.fetch.bind(window); window.fetch = (url, options) => String(url).startsWith('/api/') ? Promise.resolve(new Response(JSON.stringify({user:{id:'preview',name:'Preview',role:'admin'},projects:[{id:'central-office',name:'Central Office'}],prompts:[],skills:[],tasks:[],operations:[],workers:[],messages:[],entries:[],logs:[],tree:[],toolPermissions:{},mcpConfig:{},providerSettings:{}}),{headers:{'Content-Type':'application/json'}})) : originalFetch(url,options);`});
await send('Emulation.setDeviceMetricsOverride',{width:1440,height:960,deviceScaleFactor:1,mobile:false});
await send('Page.navigate',{url:'http://127.0.0.1:8129/index.html'}); await pause();
await evaluate(`document.querySelector('[data-settings-tab="appearance"]').click()`);
assert.equal(await evaluate(`document.querySelector('[data-settings-view="appearance"]').hidden`),false);
await evaluate(`document.querySelector('input[value="teams"]').click()`);
assert.equal(await evaluate(`document.documentElement.dataset.theme`),'teams');
assert.equal(await evaluate(`getComputedStyle(document.querySelector('.settings-panel')).backgroundColor`),'rgb(255, 255, 255)');
assert.deepEqual(await evaluate(`(() => { const r = document.querySelector('.sidebar').getBoundingClientRect(); return [r.x,r.y,r.bottom]; })()`), [0,0,960]);
assert.equal(await evaluate(`getComputedStyle(document.querySelector('.settings-panel')).borderRadius`),'10px');
assert.equal(await evaluate(`getComputedStyle(document.querySelector('.theme-option')).borderRadius`),'0px');
let shot = await send('Page.captureScreenshot',{format:'png'}); fs.writeFileSync('screenshots/teams-settings.png',Buffer.from(shot.data,'base64'));
await send('Page.navigate',{url:'http://127.0.0.1:8129/index.html'}); await pause();
assert.equal(await evaluate(`document.documentElement.dataset.theme`),'teams');
await evaluate(`document.querySelector('[data-settings-tab="appearance"]').click()`);
await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true}); await pause();
assert.equal(await evaluate(`document.documentElement.scrollWidth <= innerWidth`),true);
shot = await send('Page.captureScreenshot',{format:'png'}); fs.writeFileSync('screenshots/teams-settings-mobile.png',Buffer.from(shot.data,'base64'));
await evaluate(`document.querySelector('input[value="terminal"]').click()`);
assert.equal(await evaluate(`document.documentElement.dataset.theme`),'terminal');
await send('Page.navigate',{url:'http://127.0.0.1:8129/index.html'}); await pause();
assert.equal(await evaluate(`document.documentElement.dataset.theme`),'terminal');
await evaluate(`localStorage.setItem('agent-office-theme','invalid')`);
await send('Page.navigate',{url:'http://127.0.0.1:8129/index.html'}); await pause();
assert.equal(await evaluate(`document.documentElement.dataset.theme`),'terminal');
console.log('PASS: appearance tab, Teams styling, both theme selections and persistence, invalid value fallback, mobile overflow. Screenshots saved. API responses are isolated preview fixtures.');
await send('Browser.close'); ws.close();
